<nav>
    <ul class="nav">
        <li class="nav-header"><a href="#css">CSS</a></li>
        <li><a href="#css-grid">Grid</a></li>
        <li><a href="#css-type">Typography</a></li>
        <li><a href="#css-lists">Lists</a></li>
        <li><a href="#css-code">Code</a></li>
        <li><a href="#css-tables">Tables</a></li>
        <li><a href="#css-forms">Forms</a></li>
        <li><a href="#css-buttons">Buttons</a></li>
    </ul>
</nav>