        {# Scripts #}
        <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/2.0.2/jquery.min.js"></script>
        <!--[if lte IE 9]>
        <script src="//cdnjs.cloudflare.com/ajax/libs/flexie/1.0.0/flexie.min.js"></script>
        <![endif]-->

        <script src="/assets/vendor/holder.js"></script>
        <script src="/assets/scripts/frontkit.js"></script>
        <script src="/assets/scripts/docs.js"></script>
    </body>
</html>