        {# Scripts #}
        <!--[if lt IE 9]>
        <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/1.10.0/jquery.min.js"></script>
        <![endif]-->
        <!--[if gte IE 9> -->
        <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/2.0.2/jquery.min.js"></script>
        <!-- <![endif]-->

        <script src="assets/vendor/holder.js"></script>
        <script src="frontkit/dist/frontkit.js"></script>
        <script src="assets/scripts/docs.js"></script>
    </body>
</html>